eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:8080}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.service-registry.credentials.uri:http://127.0.0.1:8761}/eureka/

foo: bar

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80

---
spring:
  profiles: lattice
  application:
    index: ${instance.index}
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-028ba365-5d4f-4c87-a3d7-75526d020538.apps.cf.entdev.addev.ntrs.com/
  instance:
    metadataMap:
      instanceId: ${instance.guid}:${spring.application.name}:${server.port:8080}
    hostname: ${cf.instance.ip}
    nonSecurePort: ${cf.instance.port}
